module.exports = {
  GOOGLE_OAUTH: "/auth/google",
  GOOGLE_OAUTH_CALLBACK: "/auth/google/callback",
  ANCESTRIES: "/api/ancestries",
  ANCESTRIES_ID: "/api/ancestries/:id",
  BACKGROUNDS: "/api/backgrounds",
  BACKGROUNDS_ID: "/api/backgrounds/:id",
  CLASSES: "/api/classes",
  CLASSES_ID: "/api/classes/:id",
  FEATS: "/api/feats",
  FEATS_ID: "/api/feats/:id",
  ITEMS: "/api/items",
  ITEMS_ID: "/api/items/:id",
  MECHANICS: "/api/mechanics",
  MECHANICS_ID: "/api/mechanics/:id",
  MONSTERS: "/api/monsters",
  MONSTERS_ID: "/api/monsters/:id",
  PROFESSIONS: "/api/professions",
  PROFESSIONS_ID: "/api/professions/:id",
  SPELLS: "/api/spells",
  SPELLS_ID: "/api/spells/:id",
  SUBCLASSES: "/api/subclasses",
  SUBCLASSES_ID: "/api/subclasses/:id",
  USERS: "/api/users",
  USERS_ID: "/api/users/:id",
};
