const FormType = {
  ANCESTRIES: "ANCESTRIES",
  BACKGROUNDS: "BACKGROUNDS",
  CLASSES: "CLASSES",
  FEATS: "FEATS",
  ITEMS: "ITEMS",
  MECHANICS: "MECHANICS",
  MONSTERS: "MONSTERS",
  PROFESSIONS: "PROFESSIONS",
  RETAINERS: "RETAINERS",
  SPELLS: "SPELLS",
  SUBCLASSES: "SUBCLASSES",
};

export default FormType;
