const FormType = {
  ANCESTRIES: "ANCESTRIES",
  BACKGROUNDS: "BACKGROUNDS",
  CLASSES: "CLASSES",
  FEATS: "FEAT",
  ITEMS: "ITEM",
  MECHANICS: "MECHANICS",
  MONSTERS: "MONSTERS",
  PROFESSIONS: "PROFESSIONS",
  SPELLS: "SPELLS",
  SUBCLASSES: "SUBCLASSES",
};

export default FormType;
